update react and enzyme to v17
paysera/js-lib-redux-state-restore pull request #2
Opened 2022-12-19 10:01 UTC by viktor-chepyshko99

2022-12-28 09:25 UTC, yevhen-nehvey approved these changes

2023-01-12 11:17 UTC, alexnodejs requested changes

2023-01-12 11:17 UTC, alexnodejs commented on package.json
>    },
@viktor-chepyshko99, please manually bump the minor version to `1.1.0`

2023-01-12 13:38 UTC, alexnodejs approved these changes

2023-01-12 13:39 UTC, merged